//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliuComanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetaliuComanda()
        {
            this.Imagine = new HashSet<Imagine>();
        }
    
        public int Id { get; set; }
        public int ComandaId { get; set; }
        public int MaterialId { get; set; }
        public int OperatieId { get; set; }
        public int MecanicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagine> Imagine { get; set; }
        public virtual Comanda Comanda { get; set; }
        public virtual Material Material { get; set; }
        public virtual Operatie Operatie { get; set; }
        public virtual Mecanic Mecanic { get; set; }
    }
}
