//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCarService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Auto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Comanda))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.DetaliuComanda))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Imagine))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Material))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Mecanic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Operatie))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Sasiu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfCarService.ServiceReference1.Client))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Auto : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Comanda[] ComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumarAutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Sasiu SasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SasiuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieSasiuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Comanda[] Comanda {
            get {
                return this.ComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandaField, value) != true)) {
                    this.ComandaField = value;
                    this.RaisePropertyChanged("Comanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto {
            get {
                return this.NumarAutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumarAutoField, value) != true)) {
                    this.NumarAutoField = value;
                    this.RaisePropertyChanged("NumarAuto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Sasiu Sasiu {
            get {
                return this.SasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SasiuField, value) != true)) {
                    this.SasiuField = value;
                    this.RaisePropertyChanged("Sasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId {
            get {
                return this.SasiuIdField;
            }
            set {
                if ((this.SasiuIdField.Equals(value) != true)) {
                    this.SasiuIdField = value;
                    this.RaisePropertyChanged("SasiuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu {
            get {
                return this.SerieSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieSasiuField, value) != true)) {
                    this.SerieSasiuField = value;
                    this.RaisePropertyChanged("SerieSasiu");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Comanda : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Auto AutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataFinalizareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataProgramareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KmBordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StareComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValoarePieseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Auto Auto {
            get {
                return this.AutoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoField, value) != true)) {
                    this.AutoField = value;
                    this.RaisePropertyChanged("Auto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId {
            get {
                return this.AutoIdField;
            }
            set {
                if ((this.AutoIdField.Equals(value) != true)) {
                    this.AutoIdField = value;
                    this.RaisePropertyChanged("AutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFinalizare {
            get {
                return this.DataFinalizareField;
            }
            set {
                if ((this.DataFinalizareField.Equals(value) != true)) {
                    this.DataFinalizareField = value;
                    this.RaisePropertyChanged("DataFinalizare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare {
            get {
                return this.DataProgramareField;
            }
            set {
                if ((this.DataProgramareField.Equals(value) != true)) {
                    this.DataProgramareField = value;
                    this.RaisePropertyChanged("DataProgramare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem {
            get {
                return this.DataSystemField;
            }
            set {
                if ((this.DataSystemField.Equals(value) != true)) {
                    this.DataSystemField = value;
                    this.RaisePropertyChanged("DataSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KmBord {
            get {
                return this.KmBordField;
            }
            set {
                if ((this.KmBordField.Equals(value) != true)) {
                    this.KmBordField = value;
                    this.RaisePropertyChanged("KmBord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StareComanda {
            get {
                return this.StareComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.StareComandaField, value) != true)) {
                    this.StareComandaField = value;
                    this.RaisePropertyChanged("StareComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValoarePiese {
            get {
                return this.ValoarePieseField;
            }
            set {
                if ((this.ValoarePieseField.Equals(value) != true)) {
                    this.ValoarePieseField = value;
                    this.RaisePropertyChanged("ValoarePiese");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class DetaliuComanda : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Comanda ComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComandaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Imagine[] ImagineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Material MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaterialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Mecanic MecanicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MecanicIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Operatie OperatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperatieIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Comanda Comanda {
            get {
                return this.ComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandaField, value) != true)) {
                    this.ComandaField = value;
                    this.RaisePropertyChanged("Comanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId {
            get {
                return this.ComandaIdField;
            }
            set {
                if ((this.ComandaIdField.Equals(value) != true)) {
                    this.ComandaIdField = value;
                    this.RaisePropertyChanged("ComandaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Imagine[] Imagine {
            get {
                return this.ImagineField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagineField, value) != true)) {
                    this.ImagineField = value;
                    this.RaisePropertyChanged("Imagine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Material Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaterialId {
            get {
                return this.MaterialIdField;
            }
            set {
                if ((this.MaterialIdField.Equals(value) != true)) {
                    this.MaterialIdField = value;
                    this.RaisePropertyChanged("MaterialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Mecanic Mecanic {
            get {
                return this.MecanicField;
            }
            set {
                if ((object.ReferenceEquals(this.MecanicField, value) != true)) {
                    this.MecanicField = value;
                    this.RaisePropertyChanged("Mecanic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MecanicId {
            get {
                return this.MecanicIdField;
            }
            set {
                if ((this.MecanicIdField.Equals(value) != true)) {
                    this.MecanicIdField = value;
                    this.RaisePropertyChanged("MecanicId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Operatie Operatie {
            get {
                return this.OperatieField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatieField, value) != true)) {
                    this.OperatieField = value;
                    this.RaisePropertyChanged("Operatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatieId {
            get {
                return this.OperatieIdField;
            }
            set {
                if ((this.OperatieIdField.Equals(value) != true)) {
                    this.OperatieIdField = value;
                    this.RaisePropertyChanged("OperatieId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Imagine : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.DetaliuComanda DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetaliuComandaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitluField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.DetaliuComanda DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetaliuComandaId {
            get {
                return this.DetaliuComandaIdField;
            }
            set {
                if ((this.DetaliuComandaIdField.Equals(value) != true)) {
                    this.DetaliuComandaIdField = value;
                    this.RaisePropertyChanged("DetaliuComandaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu {
            get {
                return this.TitluField;
            }
            set {
                if ((object.ReferenceEquals(this.TitluField, value) != true)) {
                    this.TitluField = value;
                    this.RaisePropertyChanged("Titlu");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Material : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantitateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataAprovizionareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PretField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate {
            get {
                return this.CantitateField;
            }
            set {
                if ((this.CantitateField.Equals(value) != true)) {
                    this.CantitateField = value;
                    this.RaisePropertyChanged("Cantitate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAprovizionare {
            get {
                return this.DataAprovizionareField;
            }
            set {
                if ((this.DataAprovizionareField.Equals(value) != true)) {
                    this.DataAprovizionareField = value;
                    this.RaisePropertyChanged("DataAprovizionare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret {
            get {
                return this.PretField;
            }
            set {
                if ((this.PretField.Equals(value) != true)) {
                    this.PretField = value;
                    this.RaisePropertyChanged("Pret");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Mecanic : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Operatie : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TimpExecutieField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.DetaliuComanda[] DetaliuComanda {
            get {
                return this.DetaliuComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetaliuComandaField, value) != true)) {
                    this.DetaliuComandaField = value;
                    this.RaisePropertyChanged("DetaliuComanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimpExecutie {
            get {
                return this.TimpExecutieField;
            }
            set {
                if ((this.TimpExecutieField.Equals(value) != true)) {
                    this.TimpExecutieField = value;
                    this.RaisePropertyChanged("TimpExecutie");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Sasiu : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Auto[] AutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodSasiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Auto[] Auto {
            get {
                return this.AutoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoField, value) != true)) {
                    this.AutoField = value;
                    this.RaisePropertyChanged("Auto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu {
            get {
                return this.CodSasiuField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSasiuField, value) != true)) {
                    this.CodSasiuField = value;
                    this.RaisePropertyChanged("CodSasiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Client : WpfCarService.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Auto[] AutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfCarService.ServiceReference1.Comanda[] ComandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JudetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalitateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Auto[] Auto {
            get {
                return this.AutoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoField, value) != true)) {
                    this.AutoField = value;
                    this.RaisePropertyChanged("Auto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfCarService.ServiceReference1.Comanda[] Comanda {
            get {
                return this.ComandaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComandaField, value) != true)) {
                    this.ComandaField = value;
                    this.RaisePropertyChanged("Comanda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet {
            get {
                return this.JudetField;
            }
            set {
                if ((object.ReferenceEquals(this.JudetField, value) != true)) {
                    this.JudetField = value;
                    this.RaisePropertyChanged("Judet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate {
            get {
                return this.LocalitateField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalitateField, value) != true)) {
                    this.LocalitateField = value;
                    this.RaisePropertyChanged("Localitate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICarService")]
    public interface ICarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClients/AddClient", ReplyAction="http://tempuri.org/InterfaceClients/AddClientResponse")]
        bool AddClient(WpfCarService.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClients/AddClient", ReplyAction="http://tempuri.org/InterfaceClients/AddClientResponse")]
        System.Threading.Tasks.Task<bool> AddClientAsync(WpfCarService.ServiceReference1.Client client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarServiceChannel : WpfCarService.ServiceReference1.ICarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceClient : System.ServiceModel.ClientBase<WpfCarService.ServiceReference1.ICarService>, WpfCarService.ServiceReference1.ICarService {
        
        public CarServiceClient() {
        }
        
        public CarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddClient(WpfCarService.ServiceReference1.Client client) {
            return base.Channel.AddClient(client);
        }
        
        public System.Threading.Tasks.Task<bool> AddClientAsync(WpfCarService.ServiceReference1.Client client) {
            return base.Channel.AddClientAsync(client);
        }
    }
}
